###########################################################################################################
#                   >> IN THE NAME OF ALLAH, THE MOST GRACIOUS, THE MOST MERCIFUL <<                      #
#              EXPLOSION WAVEFORM ANALYSIS: PARTICLE VELOCITY AND TIME-DEPENDENT LOADING                  #
#---------------------------------------------------------------------------------------------------------#
#                          THIS PROGRAM WRITTEN BY SALAR DELAVAR GHASHGHAEI (QASHQAI)                     #
#                                   EMAIL: salar.d.ghashghaei@gmail.com                                   #
###########################################################################################################
"""
This Python code provides functionalities to calculate and visualize the effects of an explosion at a distance,
 focusing on both particle velocity and time-dependent loading.

The `calculate_ppv` function computes the Peak Particle Velocity (PPV) using an empirical formula that depends on
 the equivalent TNT weight ($W$), distance ($R$), and soil-specific constants ($K$ and $n$).

Two plotting functions are included:
1.  plot_particle_velocity_waveform:
    This function takes the calculated PPV and plots an exponentially decaying velocity
    waveform $v(t) = PPV \cdot e^{-\alpha t}$ over time. It marks the PPV and saves the
    plot as `particle_velocity_waveform_english.png`.
2.  plot_time_dependent_loading:
    This function visualizes a time-dependent loading function $p(t)$.
    It models $p(t)$ as being proportional to the magnitude of the acceleration 
    derived from the velocity decay, resulting in a peak load $P_{max}$ and an
    exponential decay $p(t) = P_{max} \cdot e^{-\beta t}$. The plot, saved as
    `time_dependent_loading_p_t_plot.png`, shows this loading waveform.

Both plotting functions use English labels for clarity and utilize `matplotlib`
 for visualization. Example usage demonstrates how to call these functions with
 sample parameters for TNT weight, distance, and soil constants, allowing for
 the generation of distinct plots illustrating these dynamic responses.
 The code is designed for straightforward execution and analysis of explosion effects.

---------------------------------------------------- 

To understand how an explosion several kilometers away can cause a structure to shake and potentially
 damage a building through the transmission of vibrations via the ground (Ground Shock), we need to consider a few key concepts:
Explosion Energy and Wave Generation:
An explosion, whether natural (like a volcano) or artificial (like explosives), releases a massive amount of energy suddenly.
This energy creates a very strong pressure wave in the surrounding medium (air, water, or ground). When an explosion occurs in the ground, this energy is directly transferred to the earth, generating Seismic Waves.
Types of Seismic Waves Generated by an Explosion:
Body Waves: These waves travel through the Earth’s interior. There are two main types:
P-waves (Primary Waves or Compressional Waves): These are the fastest waves and cause particles in the ground to compress and expand in the direction of wave propagation. They are similar to sound waves.
S-waves (Secondary Waves or Shear Waves): These waves are slower than P-waves and cause particles in the ground to move perpendicular to the direction of wave propagation. They are like waves in a shaken rope.
Surface Waves: These waves travel along the Earth’s surface and are typically slower than body waves but have larger amplitudes, making them often more destructive. There are two main types:
Love Waves: These cause horizontal shearing of the ground.
Rayleigh Waves: These cause elliptical particle motion in a vertical plane, similar to waves on the sea.
Energy Transmission and Attenuation:
As seismic waves travel away from the explosion’s origin, their energy decreases due to spreading over a larger volume and absorption by the earth’s materials. This phenomenon is called attenuation.
The greater the distance from the explosion, the smaller the amplitude of the vibrations and, consequently, the weaker the impact on the structure. However, this attenuation also depends on the geological characteristics of the ground.
Ground Shock:
The term “Ground Shock” generally refers to the vibrations generated in the ground by an impact source (like an explosion, the fall of a heavy object, or even heavy vehicle traffic).
In the case of an explosion, Ground Shock encompasses all the seismic waves (P, S, Love, Rayleigh) that emanate from the blast and propagate through the ground.
The intensity of this shock is measured by parameters such as Peak Particle Velocity (PPV) and Peak Particle Acceleration (PPA).
Impact on Structures:
When seismic waves reach a building’s foundation, they transmit vibrations to the entire structure.
If the intensity of these vibrations (especially their frequency and amplitude) matches the building’s natural frequency, a phenomenon called resonance can occur. In this situation, even relatively weak vibrations can cause a significant increase in the building’s motion amplitude, potentially leading to severe damage or collapse.
A distance of several kilometers, depending on the magnitude of the explosion and ground conditions, can still be close enough for vibrations to be strong enough to interact with a structure and, if resonance occurs, cause shaking and damage.

"""
import numpy as np
import matplotlib.pyplot as plt
#%%----------------------------------------------------
def calculate_ppv(W_kg, R_m, K, n):
  """
  Calculates the Peak Particle Velocity (PPV) from an explosion.

  Args:
    W_kg: Equivalent weight of TNT in kilograms.
    R_m: Distance from the explosion in meters.
    K: Empirical constant related to soil type.
    n: Empirical exponent related to soil type.

  Returns:
    The PPV in meters per second (m/s).
  """
  if R_m <= 0:
    return float('inf') # Avoid division by zero or non-physical distances
  
  ppv = K * (W_kg **(1/3) / R_m)**n
  return ppv
#%%----------------------------------------------------
def plot_time_dependent_loading(W_kg, R_m, K, n, alpha_decay=30, t_end=0.5, P_max_scale=1.0):
  """
  Calculates and plots a time-dependent loading waveform p(t) over time.
  This assumes p(t) is proportional to the magnitude of the acceleration derived 
  from the particle velocity decay, scaled by P_max_scale.

  Args:
    W_kg: Equivalent weight of TNT in kilograms.
    R_m: Distance from the explosion in meters.
    K: Empirical constant.
    n: Empirical exponent.
    alpha_decay: Decay constant for the waveform (can be related to velocity decay).
    t_end: End time for the plot (seconds).
    P_max_scale: A scaling factor to determine the peak of the loading function.
                 This would typically be derived from mass and acceleration.
                 Here, it's used to set the amplitude of p(t).
  """
  ppv = calculate_ppv(W_kg, R_m, K, n)
  
  if ppv == float('inf'):
      print("Error: Distance must be positive.")
      return

  # Define the time vector
  t = np.linspace(0, t_end, 500)
  
  # --- Model for p(t) ---
  # We can model p(t) as being proportional to the magnitude of acceleration.
  # If v(t) = PPV * exp(-alpha_decay * t), then a(t) = -alpha_decay * PPV * exp(-alpha_decay * t)
  # The magnitude of acceleration is |a(t)| = alpha_decay * PPV * exp(-alpha_decay * t)
  # Let's define P_max as the peak loading, which we can scale relative to PPV and alpha.
  # For demonstration, let's set P_max = P_max_scale * alpha_decay * PPV
  # And the load function p(t) = P_max * exp(-alpha_decay * t)
  
  P_max = P_max_scale * alpha_decay * ppv # Scaling factor for peak load
  
  p_t = P_max * np.exp(-alpha_decay * t)

  # --- Plotting ---
  plt.figure(figsize=(10, 6))
  
  # Plotting the loading waveform
  plt.plot(t, p_t, label=f'Loading $p(t)$')
  
  # Mark P_max
  # The peak load occurs at t=0 in this model
  plt.plot(0, P_max, 'bo', markersize=8, label=f'Peak Load $P_{max}$ = {P_max:.2f} N (or consistent units)') 
  plt.vlines(0, 0, P_max, colors='b', linestyles='dashed', alpha=0.7)

  # English labels for the plot
  plt.title("Time-Dependent Loading Waveform $p(t)$", fontsize=16)
  plt.xlabel("Time (s)", fontsize=12)
  plt.ylabel("Loading (Units of Force)", fontsize=12) # Assuming force units
  
  plt.legend()
  plt.grid(True, linestyle='--', alpha=0.6)
  plt.ylim(bottom=0) # Ensure y-axis starts from 0
  plt.xlim(left=0)
  
  # Save the plot
  #plot_filename = "[/mnt/data/time_dependent_loading_p_t_plot.png"](https://storage.gapgpt.app/media/code_interpreter/e7c62e0b-f103-436d-99c2-1c7cf6cebc98/time_dependent_loading_p_t_plot.png%22)
  #plt.savefig(plot_filename)
  #print(f"Plot saved to: {plot_filename}")
  plt.show()
#%%----------------------------------------------------  
def plot_particle_velocity_waveform(W_kg, R_m, K, n, alpha=30, t_end=0.5):
  """
  Calculates and plots the particle velocity waveform over time using English labels.

  Args:
    W_kg: Equivalent weight of TNT in kilograms.
    R_m: Distance from the explosion in meters.
    K: Empirical constant.
    n: Empirical exponent.
    alpha: Decay constant for the velocity waveform (1/s).
    t_end: End time for the plot (seconds).
  """
  ppv = calculate_ppv(W_kg, R_m, K, n)
  
  if ppv == float('inf'):
      print("Error: Distance must be positive.")
      return

  # Time vector
  t = np.linspace(0, t_end, 500)
  # Velocity waveform (exponential decay model)
  v_t = ppv * np.exp(-alpha * t)

  # --- Plotting ---
  plt.figure(figsize=(10, 6))
  
  # Plotting the waveform
  plt.plot(t, v_t, label=f'Velocity $v(t)$')
  
  # Mark PPV
  # For this waveform model, PPV occurs at t=0
  plt.plot(0, ppv, 'ro', markersize=8, label=f'PPV = {ppv:.4f} m/s') 
  plt.vlines(0, 0, ppv, colors='r', linestyles='dashed', alpha=0.7)

  # English labels for the plot
  plt.title("Particle Velocity Waveform Over Time", fontsize=16)
  plt.xlabel("Time (s)", fontsize=12)
  plt.ylabel("Particle Velocity (m/s)", fontsize=12)
  
  plt.legend()
  plt.grid(True, linestyle='--', alpha=0.6)
  plt.ylim(bottom=0) # Ensure y-axis starts from 0
  plt.xlim(left=0)
  
  # Save the plot
  #plot_filename = "[/mnt/data/particle_velocity_waveform_english.png"](https://storage.gapgpt.app/media/code_interpreter/e7c62e0b-f103-436d-99c2-1c7cf6cebc98/particle_velocity_waveform_english.png%22)
  #plt.savefig(plot_filename)
  #print(f"Plot saved to: {plot_filename}")
  plt.show()  
#%%----------------------------------------------------
# --- Example Usage ---
W_example = 1000   # 1 Ton TNT
R_example = 5000   # meters
K_medium_soil = 200
n_medium_soil = 1.6
plot_particle_velocity_waveform(W_example, R_example, K_medium_soil, n_medium_soil, alpha=30, t_end=0.5)

# Adjust P_max_scale to set the amplitude of the loading. 
# A value of 1.0 means P_max is roughly alpha*PPV.
# You might need to adjust this based on the actual mass 'm' if you want to represent F_max = m*a_max.
plot_time_dependent_loading(W_example, R_example, K_medium_soil, n_medium_soil, alpha_decay=30, t_end=0.5, P_max_scale=1.0)
#%%----------------------------------------------------